In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('../scripts/')
from faster_rcnn_vgg16 import decom_vgg16
import torch.nn as nn
from bbox_tools import generate_anchor_base

In [2]:
features, classifier = decom_vgg16()

In [3]:
nn.Conv2d(512, 512, 3, 1, 1)

Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [ ]:
# generate_anchor_base()

array([[ -37.254833,  -82.50967 ,   53.254833,   98.50967 ],
       [ -82.50967 , -173.01933 ,   98.50967 ,  189.01933 ],
       [-173.01933 , -354.03867 ,  189.01933 ,  370.03867 ],
       [ -56.      ,  -56.      ,   72.      ,   72.      ],
       [-120.      , -120.      ,  136.      ,  136.      ],
       [-248.      , -248.      ,  264.      ,  264.      ],
       [ -82.50967 ,  -37.254833,   98.50967 ,   53.254833],
       [-173.01933 ,  -82.50967 ,  189.01933 ,   98.50967 ],
       [-354.03867 , -173.01933 ,  370.03867 ,  189.01933 ]],
      dtype=float32)

In [4]:
import torch

In [6]:
test_layer = torch.nn.Linear(1, 1)

In [8]:
def normal_init(m, mean, stddev, truncated=False):
    """
    weight initalizer: truncated normal and random normal.
    """
    # x is a parameter
    if truncated:
        m.weight.data.normal_().fmod_(2).mul_(stddev).add_(mean)  # not a perfect approximation
    else:
        m.weight.data.normal_(mean, stddev)
        m.bias.data.zero_()

In [11]:
normal_init(test_layer, 0, 0.001)

In [12]:
test_layer.weight

Parameter containing:
tensor([[9.6999e-05]], requires_grad=True)

In [43]:
import torch
import numpy as np

In [46]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [63]:
temp = torch.arange(0, 8)

In [64]:
temp = temp.reshape(2, 4)

In [71]:
class Circle:
    def __init__(self, radius):
        self.radius = radius

    @property
    def area(self):
        return 3.14 * self.radius ** 2

In [72]:
temp = Circle(3)

In [79]:
temp.area

28.26

In [81]:
print('Hello')

Hello
